"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { LoadingScreen } from "@/components/LoadingScreen";
import { LeagueNav } from "@/components/LeagueNav";
import { useLeague } from "@/lib/league-context";
import {
  GroupStageView,
  MatchCard,
  RoundColumn,
  SurvivalTable,
  type SurvivalDisplay,
  type TieDisplay,
  usePlayoffsBracket,
} from "./shared";

type TabType = "tvt" | "challenger" | "groupStage";

export function ClassicPlayoffs() {
  const params = useParams();
  const leagueSlug = params.leagueSlug as string;

  const { league, viewer } = useLeague();
  const leagueName = league.name;
  const leagueFormat = league.format;
  const isLoggedIn = viewer.authenticated;
  const dashboardHref = viewer.dashboardHref;

  const { data, isLoading, refreshing, tempLiveScores, handleRefreshRound } = usePlayoffsBracket(leagueSlug);
  const [activeTab, setActiveTab] = useState<TabType>("tvt");

  useEffect(() => {
    if (data && data.teamSize === 16 && data.latestCompletedGw < 34) {
      setActiveTab("groupStage");
    }
  }, [data]);

  const handleSignOut = async () => {
    await fetch("/api/auth/signout", { method: "POST" });
    window.location.href = "/signin";
  };

  if (isLoading) return <LoadingScreen variant="playoffs" />;

  if (!data) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-slate-900 via-purple-900 to-slate-900 flex items-center justify-center">
        <div className="text-red-400 text-xl">Failed to load playoffs bracket</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 via-purple-900 to-slate-900">
      <LeagueNav
        leagueSlug={leagueSlug}
        leagueName={leagueName}
        currentPage="playoffs"
        format={leagueFormat === "auction" ? "auction" : "tvt"}
        isLoggedIn={isLoggedIn}
        dashboardHref={dashboardHref}
        onSignOut={handleSignOut}
      />

      <div className="mx-auto max-w-7xl px-6 py-8">
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-white mb-2">Playoffs Bracket</h1>
          {data.mode === "tentative" && (
            <div className="inline-flex items-center gap-2 bg-yellow-500/20 border border-yellow-500/40 rounded-lg px-4 py-2">
              <span className="text-yellow-400 text-sm font-semibold">&#9888; TENTATIVE</span>
              <span className="text-yellow-200/80 text-sm">Projected from current standings. Fixtures lock after GW30.</span>
            </div>
          )}
          {data.mode === "projected" && (
            <div className="inline-flex items-center gap-2 bg-blue-500/20 border border-blue-500/40 rounded-lg px-4 py-2">
              <span className="text-blue-400 text-sm font-semibold">Based on final group standings</span>
              <span className="text-blue-200/80 text-sm">Fixtures will be generated by admin shortly.</span>
            </div>
          )}
        </div>

        {data.teamSize === 16 && (
          <div className="flex gap-1 mb-6 bg-slate-800/50 rounded-lg p-1 w-fit flex-wrap">
            <button
              onClick={() => setActiveTab("groupStage")}
              className={`px-4 py-2 rounded-md text-sm font-semibold transition ${
                activeTab === "groupStage" ? "bg-yellow-500 text-slate-900" : "text-gray-400 hover:text-white"
              }`}
            >
              Group Stage
            </button>
            <button
              onClick={() => setActiveTab("tvt")}
              className={`px-4 py-2 rounded-md text-sm font-semibold transition ${
                activeTab === "tvt" ? "bg-yellow-500 text-slate-900" : "text-gray-400 hover:text-white"
              }`}
            >
              TVT Main Draw
            </button>
            <button
              onClick={() => setActiveTab("challenger")}
              className={`px-4 py-2 rounded-md text-sm font-semibold transition ${
                activeTab === "challenger" ? "bg-yellow-500 text-slate-900" : "text-gray-400 hover:text-white"
              }`}
            >
              Challenger Series
            </button>
          </div>
        )}
        {data.teamSize === 32 && (
          <div className="flex gap-1 mb-6 bg-slate-800/50 rounded-lg p-1 w-fit flex-wrap">
            <button
              onClick={() => setActiveTab("tvt")}
              className={`px-4 py-2 rounded-md text-sm font-semibold transition ${
                activeTab === "tvt" ? "bg-yellow-500 text-slate-900" : "text-gray-400 hover:text-white"
              }`}
            >
              TVT Main Draw
            </button>
            <button
              onClick={() => setActiveTab("challenger")}
              className={`px-4 py-2 rounded-md text-sm font-semibold transition ${
                activeTab === "challenger" ? "bg-yellow-500 text-slate-900" : "text-gray-400 hover:text-white"
              }`}
            >
              Challenger Series
            </button>
          </div>
        )}

        {activeTab === "groupStage" && data.teamSize === 16 && data.groupStage && (
          <GroupStageView
            groups={data.groupStage.groups}
            liveScores={data.liveScores}
            refreshingGw={refreshing}
            tempLiveScores={tempLiveScores}
            onRefreshRound={handleRefreshRound}
            playoffStartGw={31}
            latestCompletedGw={data.latestCompletedGw}
          />
        )}

        {(activeTab === "tvt" || data.teamSize === 8) && (
          <div className="overflow-x-auto -mx-4 px-4 sm:mx-0 sm:px-0">
            {data.teamSize === 8 ? (
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 min-w-[480px]">
                <RoundColumn title="Semi-Finals" ties={data.tvt.sf ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                <RoundColumn title="3rd Place" ties={data.tvt.thirdPlace ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                <RoundColumn title="Final" ties={data.tvt.final ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
              </div>
            ) : data.teamSize === 16 ? (
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 min-w-[600px] min-h-[500px]">
                <RoundColumn title="Seeding Round" ties={data.tvt.qf ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                <RoundColumn title="Semi-Finals" ties={data.tvt.sf ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                <RoundColumn title="Grand Finale" ties={data.tvt.final ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
              </div>
            ) : (
              <div className="grid grid-cols-4 gap-3 sm:gap-4 min-w-[700px] min-h-[600px]">
                <RoundColumn title="Round of 16" ties={data.tvt.ro16 ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                <RoundColumn title="Quarter-Finals" ties={data.tvt.qf ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                <RoundColumn title="Semi-Finals" ties={data.tvt.sf ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                <RoundColumn title="Grand Finale" ties={data.tvt.final ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
              </div>
            )}
          </div>
        )}

        {activeTab === "challenger" && data.teamSize !== 8 && (
          <div className="space-y-6">
            {(() => {
              const allLiveScores = data.liveScores ? Object.values(data.liveScores).flat() : [];
              const tempScores = tempLiveScores ? Object.values(tempLiveScores).flat() : [];
              const mergedScores = [...tempScores, ...allLiveScores];

              const challengerRounds = data.teamSize === 16 ? [
                { key: "c34", label: "Challenger QFs (GW34)", gw: 34, data: data.challenger.c34 },
                { key: "c35", label: "Challenger Semi-Finals (GW35–36)", gw: 35, data: data.challenger.c35 },
                { key: "c36", label: "Challenger Final (GW37–38)", gw: 37, data: data.challenger.c36 },
              ] : [
                { key: "c31", label: "C-31 (GW31) — Round of 12", gw: 31, data: data.challenger.c31 },
                { key: "c32", label: "C-32 (GW32) — Round of 6", gw: 32, data: data.challenger.c32 },
                { key: "c34", label: "C-34 (GW34) — Quarter-Finals", gw: 34, data: data.challenger.c34 },
                { key: "c35", label: "C-35 (GW35) — QF Losers vs C-34 Winners", gw: 35, data: data.challenger.c35 },
                { key: "c36", label: "C-36 (GW36) — Round of 4", gw: 36, data: data.challenger.c36 },
                { key: "c37", label: "C-37 (GW37) — Challenger Semi-Finals", gw: 37, data: data.challenger.c37 },
                { key: "c38", label: "C-38 (GW38) — Challenger Final", gw: 38, data: data.challenger.c38 },
              ];

              const hasAnyChallengerRound = challengerRounds.some((r) => (r.data as TieDisplay[])?.length > 0);

              return (
                <>
                  {data.teamSize === 32 && (data.challenger.c33?.length ?? 0) > 0 && (
                    <SurvivalTable entries={data.challenger.c33 as SurvivalDisplay[]} />
                  )}
                  {data.teamSize === 16 && !hasAnyChallengerRound && (
                    <div className="bg-slate-800/50 border border-slate-700 rounded-lg p-6 text-center">
                      <p className="text-gray-400 text-sm mb-2">⏳ Challenger fixtures will be available after group stage (GW33) completes.</p>
                      <p className="text-gray-500 text-xs">Once admin advances playoffs, Top 2 from each Challenger Group will play QFs in GW34.</p>
                    </div>
                  )}
                  {challengerRounds.map(({ key, label, gw, data: roundData }) => {
                    const ties = roundData as TieDisplay[];
                    if (!ties || ties.length === 0) return null;
                    const hasLive = mergedScores.some((s) => s.gameweek === gw);
                    const isRoundRefreshing = refreshing === gw;
                    return (
                      <div key={key}>
                        <div className="flex items-center gap-2 mb-2">
                          <h3 className="text-xs font-bold text-yellow-400 uppercase tracking-wider">{label}</h3>
                          {hasLive && (
                            <button
                              onClick={() => handleRefreshRound(gw)}
                              disabled={isRoundRefreshing}
                              className={`text-green-400 hover:text-green-300 disabled:opacity-50 transition-all text-sm ${isRoundRefreshing ? "animate-spin" : ""}`}
                              title="Refresh live scores"
                            >
                              ⟳
                            </button>
                          )}
                        </div>
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                          {ties.map((tie) => (
                            <MatchCard key={tie.tieId} tie={tie} compact liveScores={mergedScores} />
                          ))}
                        </div>
                      </div>
                    );
                  })}
                </>
              );
            })()}
          </div>
        )}
      </div>
    </div>
  );
}
