"use client";

import { useState } from "react";
import { useParams } from "next/navigation";
import { LoadingScreen } from "@/components/LoadingScreen";
import { LeagueNav } from "@/components/LeagueNav";
import { Tabs } from "@/components/ui/Tabs";
import { useLeague } from "@/lib/league-context";
import {
  GroupStageView,
  MatchCard,
  RoundColumn,
  SurvivalTable,
  type SurvivalDisplay,
  type TieDisplay,
  usePlayoffsBracket,
} from "./shared";

type TabType = "tvt" | "challenger" | "groupStage";
type Ro32Round = "ro16" | "qf" | "sf" | "final";

export function ClassicPlayoffs() {
  const params = useParams();
  const leagueSlug = params.leagueSlug as string;

  const { league, viewer } = useLeague();
  const leagueName = league.name;
  const leagueFormat = league.format;
  const isLoggedIn = viewer.authenticated;
  const dashboardHref = viewer.dashboardHref;

  const { data, isLoading, refreshing, tempLiveScores, handleRefreshRound } = usePlayoffsBracket(leagueSlug);
  // Derive the active tab from data + an optional user override. The 16-team variant defaults to
  // "groupStage" while early playoff GWs haven't finished, but the user can manually switch and the
  // override sticks. Computing at render-time avoids a setState-in-effect cascade.
  const [tabOverride, setTabOverride] = useState<TabType | null>(null);
  const autoDefaultTab: TabType = data && data.teamSize === 16 && data.latestCompletedGw < 34 ? "groupStage" : "tvt";
  const activeTab: TabType = tabOverride ?? autoDefaultTab;
  const setActiveTab = (t: TabType) => setTabOverride(t);
  // Phones show the 32-team main draw one round at a time; wider screens show all four columns.
  const [ro32Round, setRo32Round] = useState<Ro32Round | null>(null);

  const handleSignOut = async () => {
    await fetch("/api/auth/signout", { method: "POST" });
    window.location.href = "/signin";
  };

  if (isLoading) return <LoadingScreen variant="playoffs" />;

  if (!data) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-slate-900 via-purple-900 to-slate-900 flex items-center justify-center">
        <div className="text-red-400 text-xl">Failed to load playoffs bracket</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 via-purple-900 to-slate-900">
      <LeagueNav
        leagueSlug={leagueSlug}
        leagueName={leagueName}
        currentPage="playoffs"
        format={leagueFormat === "auction" ? "auction" : "tvt"}
        teamSize={league.teamSize}
        isLoggedIn={isLoggedIn}
        dashboardHref={dashboardHref}
        onSignOut={handleSignOut}
      />

      <div className="mx-auto max-w-7xl px-4 sm:px-6 py-6 sm:py-8">
        <div className="mb-4 sm:mb-6">
          <h1 className="text-2xl sm:text-3xl font-bold text-white mb-2">Playoffs Bracket</h1>
          {data.mode === "tentative" && (
            <div className="inline-flex items-center gap-2 bg-yellow-500/20 border border-yellow-500/40 rounded-lg px-4 py-2">
              <span className="text-yellow-400 text-sm font-semibold">&#9888; TENTATIVE</span>
              <span className="text-yellow-200/80 text-sm">Projected from current standings. Fixtures lock after GW{league.playoffStartGw - 1}.</span>
            </div>
          )}
          {data.mode === "projected" && (
            <div className="inline-flex items-center gap-2 bg-blue-500/20 border border-blue-500/40 rounded-lg px-4 py-2">
              <span className="text-blue-400 text-sm font-semibold">Based on final group standings</span>
              <span className="text-blue-200/80 text-sm">Fixtures will be generated by admin shortly.</span>
            </div>
          )}
        </div>

        {(data.teamSize === 16 || data.teamSize === 32) && (
          <Tabs<TabType>
            variant="pill"
            ariaLabel="Bracket"
            className="mb-4 sm:mb-6 sm:w-fit"
            value={activeTab}
            onChange={setActiveTab}
            items={[
              ...(data.teamSize === 16 ? [{ id: "groupStage" as const, label: "Group Stage" }] : []),
              { id: "tvt", label: "TVT Main Draw" },
              { id: "challenger", label: "Challenger Series" },
            ]}
          />
        )}

        {activeTab === "groupStage" && data.teamSize === 16 && data.groupStage && (
          <GroupStageView
            groups={data.groupStage.groups}
            liveScores={data.liveScores}
            refreshingGw={refreshing}
            tempLiveScores={tempLiveScores}
            onRefreshRound={handleRefreshRound}
            playoffStartGw={31}
            latestCompletedGw={data.latestCompletedGw}
          />
        )}

        {(activeTab === "tvt" || data.teamSize === 8) && (
          <div>
            {data.teamSize === 8 ? (
              <div className="space-y-8">
                <div>
                  <h2 className="text-xs font-bold text-yellow-400 uppercase tracking-wider mb-3">GW36 — Semi-Finals</h2>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <RoundColumn title="Semi-Finals" ties={data.tvt.sf ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                  </div>
                </div>
                <div>
                  <h2 className="text-xs font-bold text-yellow-400 uppercase tracking-wider mb-3">GW37–38 — Final &amp; 3rd Place</h2>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <RoundColumn title="Final" ties={data.tvt.final ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                    <RoundColumn title="3rd Place" ties={data.tvt.thirdPlace ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                  </div>
                </div>
              </div>
            ) : data.teamSize === 16 ? (
              <div className="space-y-8">
                <div>
                  <h2 className="text-xs font-bold text-yellow-400 uppercase tracking-wider mb-3">GW34–35 — Semi-Finals</h2>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <RoundColumn title="Semi-Finals" ties={data.tvt.sf ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                  </div>
                </div>
                <div>
                  <h2 className="text-xs font-bold text-yellow-400 uppercase tracking-wider mb-3">GW36–38 — Final &amp; 3rd Place (Triple-Legged Aggregate)</h2>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <RoundColumn title="Final" ties={data.tvt.final ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                    <RoundColumn title="3rd Place" ties={data.tvt.thirdPlace ?? []} liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} />
                  </div>
                </div>
              </div>
            ) : (
              (() => {
                const rounds: { id: Ro32Round; title: string; short: string; ties: TieDisplay[] }[] = [
                  { id: "ro16", title: "Round of 16", short: "R16", ties: data.tvt.ro16 ?? [] },
                  { id: "qf", title: "Quarter-Finals", short: "QF", ties: data.tvt.qf ?? [] },
                  { id: "sf", title: "Semi-Finals", short: "SF", ties: data.tvt.sf ?? [] },
                  { id: "final", title: "Grand Finale", short: "Final", ties: data.tvt.final ?? [] },
                ];
                const played = rounds.filter((r) => r.ties.length > 0);
                // Default to the latest round whose matchups are known (both teams decided) — the
                // one people are following. A tentative bracket fills later rounds with
                // "Winner of …" placeholders, so it opens on the first round instead.
                // A side with no teamId is a placeholder (same test MatchCard uses).
                const decided = played.filter((r) => r.ties.some((t) => t.home?.teamId && t.away?.teamId));
                const current =
                  played.find((r) => r.id === ro32Round)?.id ??
                  decided[decided.length - 1]?.id ??
                  played[0]?.id;
                return (
                  <>
                    {played.length > 1 && (
                      <Tabs<Ro32Round>
                        ariaLabel="Round"
                        className="mb-4 md:hidden"
                        value={current ?? "ro16"}
                        onChange={setRo32Round}
                        items={played.map((r) => ({ id: r.id, label: r.short }))}
                      />
                    )}
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-3 sm:gap-4 md:min-h-[600px]">
                      {rounds.map((r) => (
                        <RoundColumn
                          key={r.id}
                          title={r.title}
                          ties={r.ties}
                          className={r.id === current ? "" : "hidden md:flex"}
                          liveScores={data.liveScores}
                          refreshingGw={refreshing}
                          tempLiveScores={tempLiveScores}
                          onRefreshRound={handleRefreshRound}
                        />
                      ))}
                    </div>
                  </>
                );
              })()
            )}
          </div>
        )}

        {activeTab === "challenger" && data.teamSize !== 8 && (
          <div className="space-y-6">
            {(() => {
              const allLiveScores = data.liveScores ? Object.values(data.liveScores).flat() : [];
              const tempScores = tempLiveScores ? Object.values(tempLiveScores).flat() : [];
              const mergedScores = [...tempScores, ...allLiveScores];

              const challengerRounds = data.teamSize === 16 ? [
                { key: "c34", label: "Challenger QFs (GW34)", gw: 34, data: data.challenger.c34 },
                { key: "c35", label: "Challenger Semi-Finals (GW35–36)", gw: 35, data: data.challenger.c35 },
                { key: "c36", label: "Challenger Final (GW37–38)", gw: 37, data: data.challenger.c36 },
              ] : [
                { key: "c31", label: "C-31 (GW31) — Round of 12", gw: 31, data: data.challenger.c31 },
                { key: "c32", label: "C-32 (GW32) — Round of 6", gw: 32, data: data.challenger.c32 },
                { key: "c34", label: "C-34 (GW34) — Quarter-Finals", gw: 34, data: data.challenger.c34 },
                { key: "c35", label: "C-35 (GW35) — QF Losers vs C-34 Winners", gw: 35, data: data.challenger.c35 },
                { key: "c36", label: "C-36 (GW36) — Round of 4", gw: 36, data: data.challenger.c36 },
                { key: "c37", label: "C-37 (GW37) — Challenger Semi-Finals", gw: 37, data: data.challenger.c37 },
                { key: "c38", label: "C-38 (GW38) — Challenger Final", gw: 38, data: data.challenger.c38 },
              ];

              const hasAnyChallengerRound = challengerRounds.some((r) => (r.data as TieDisplay[])?.length > 0);

              const showSurvival = data.teamSize === 32 && (data.challenger.c33?.length ?? 0) > 0;

              return (
                <>
                  {data.teamSize === 16 && !hasAnyChallengerRound && (
                    <div className="bg-slate-800/50 border border-slate-700 rounded-lg p-6 text-center">
                      <p className="text-gray-400 text-sm mb-2">⏳ Challenger fixtures will be available after group stage (GW33) completes.</p>
                      <p className="text-gray-500 text-xs">Once admin advances playoffs, Top 2 from each Challenger Group will play QFs in GW34.</p>
                    </div>
                  )}
                  {challengerRounds.map(({ key, label, gw, data: roundData }) => {
                    const ties = roundData as TieDisplay[];
                    const insertSurvivalBefore = key === "c34" && showSurvival;
                    if ((!ties || ties.length === 0) && !insertSurvivalBefore) return null;
                    const roundGws = ties && ties.length > 0
                      ? Array.from(new Set(ties.flatMap(t => [t.gw1, t.gw2, t.gw3].filter((x): x is number => x != null))))
                      : [gw];
                    const hasLive = mergedScores.some((s) => roundGws.includes(s.gameweek));
                    const isRoundRefreshing = refreshing != null && roundGws.includes(refreshing);
                    return (
                      <div key={key} className="space-y-6">
                        {insertSurvivalBefore && (
                          <SurvivalTable
                            entries={data.challenger.c33 as SurvivalDisplay[]}
                            onRefresh={() => handleRefreshRound(33)}
                            isRefreshing={refreshing === 33}
                          />
                        )}
                        {ties && ties.length > 0 && (
                          <div>
                            <div className="flex items-center gap-2 mb-2">
                              <h3 className="text-xs font-bold text-yellow-400 uppercase tracking-wider">{label}</h3>
                              {hasLive && (
                                <button
                                  onClick={() => roundGws.forEach(g => handleRefreshRound(g))}
                                  disabled={isRoundRefreshing}
                                  className={`text-green-400 hover:text-green-300 disabled:opacity-50 transition-all text-sm ${isRoundRefreshing ? "animate-spin" : ""}`}
                                  title="Refresh live scores"
                                >
                                  ⟳
                                </button>
                              )}
                            </div>
                            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                              {ties.map((tie) => (
                                <MatchCard key={tie.tieId} tie={tie} compact liveScores={mergedScores} />
                              ))}
                            </div>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </>
              );
            })()}
          </div>
        )}
      </div>
    </div>
  );
}
