"use client";

import { useState } from "react";
import { useParams } from "next/navigation";
import { LoadingScreen } from "@/components/LoadingScreen";
import { LeagueNav } from "@/components/LeagueNav";
import { useLeague } from "@/lib/league-context";
import { RoundColumn, usePlayoffsBracket } from "./shared";

export function TripleCrownPlayoffs() {
  const params = useParams();
  const leagueSlug = params.leagueSlug as string;

  const { league, viewer } = useLeague();
  const leagueName = league.name;
  const isLoggedIn = viewer.authenticated;
  const dashboardHref = viewer.dashboardHref;

  const { data, isLoading, refreshing, tempLiveScores, handleRefreshRound } = usePlayoffsBracket(leagueSlug);
  const [tcTab, setTcTab] = useState<"jcl" | "jel">("jcl");

  const handleSignOut = async () => {
    await fetch("/api/auth/signout", { method: "POST" });
    window.location.href = "/signin";
  };

  if (isLoading) return <LoadingScreen variant="playoffs" />;

  if (!data) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-slate-900 via-purple-900 to-slate-900 flex items-center justify-center">
        <div className="text-red-400 text-xl">Failed to load playoffs bracket</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 via-purple-900 to-slate-900">
      <LeagueNav
        leagueSlug={leagueSlug}
        leagueName={leagueName}
        currentPage="playoffs"
        format="continental-championship"
        isLoggedIn={isLoggedIn}
        dashboardHref={dashboardHref}
        onSignOut={handleSignOut}
      />

      <div className="mx-auto max-w-7xl px-3 sm:px-6 py-6 sm:py-8">
        <div className="mb-4 sm:mb-6">
          <h1 className="text-2xl sm:text-3xl font-bold text-white mb-2">Knockout Stage</h1>
          <p className="text-gray-400 text-xs sm:text-sm">JPL Champions League &amp; JPL Europa League · Continental Championship</p>
          {data.mode === "tentative" && (
            <div className="mt-2 inline-flex items-center gap-2 bg-yellow-500/20 border border-yellow-500/40 rounded-lg px-4 py-2">
              <span className="text-yellow-400 text-sm font-semibold">&#9888; TENTATIVE</span>
              <span className="text-yellow-200/80 text-sm">Projected from current cup-group standings. Brackets lock after the group stage.</span>
            </div>
          )}
          {data.mode === "projected" && (
            <div className="mt-2 inline-flex items-center gap-2 bg-blue-500/20 border border-blue-500/40 rounded-lg px-4 py-2">
              <span className="text-blue-400 text-sm font-semibold">Based on final group standings</span>
              <span className="text-blue-200/80 text-sm">Brackets will be generated by admin shortly.</span>
            </div>
          )}
        </div>

        <div className="flex gap-1 mb-6 sm:mb-8 bg-slate-800/50 rounded-lg p-1 w-full sm:w-fit">
          <button
            onClick={() => setTcTab("jcl")}
            className={`flex-1 sm:flex-none px-4 sm:px-5 py-1.5 sm:py-2 rounded-md text-xs sm:text-sm font-semibold transition ${
              tcTab === "jcl" ? "bg-blue-600 text-white" : "text-gray-400 hover:text-white"
            }`}
          >
            ★ JCL
          </button>
          <button
            onClick={() => setTcTab("jel")}
            className={`flex-1 sm:flex-none px-4 sm:px-5 py-1.5 sm:py-2 rounded-md text-xs sm:text-sm font-semibold transition ${
              tcTab === "jel" ? "bg-orange-600 text-white" : "text-gray-400 hover:text-white"
            }`}
          >
            ◆ JPL Europa League
          </button>
        </div>

        {tcTab === "jcl" && (
          <div>
            <div className="flex items-center gap-3 mb-4 sm:mb-6">
              <div className="h-8 w-1 rounded-full bg-blue-500" />
              <div>
                <h2 className="text-lg sm:text-xl font-bold text-white">JCL Knockouts</h2>
                <p className="text-blue-400 text-[10px] sm:text-xs font-semibold uppercase tracking-wider">JPL Champions League</p>
              </div>
            </div>
            {(data.tvt.qf?.length || data.tvt.sf?.length || data.tvt.final?.length) ? (
              <div className="overflow-x-auto -mx-4 px-4 sm:mx-0 sm:px-0">
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 min-w-[480px]">
                  <RoundColumn title="Quarter-Finals" ties={data.tvt.qf ?? []}liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} className="border-l-2 border-blue-500/30 pl-3" />
                  <RoundColumn title="Semi-Finals" ties={data.tvt.sf ?? []}liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} className="border-l-2 border-blue-500/30 pl-3" />
                  <RoundColumn title="JCL Final 🏆" ties={data.tvt.final ?? []}liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} className="border-l-2 border-yellow-500/50 pl-3" />
                </div>
              </div>
            ) : (
              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 px-5 py-6 text-sm text-blue-300">
                JCL bracket will be generated after the group stage (GW24).
              </div>
            )}
          </div>
        )}

        {tcTab === "jel" && (
          <div>
            <div className="flex items-center gap-3 mb-6">
              <div className="h-8 w-1 rounded-full bg-orange-500" />
              <div>
                <h2 className="text-xl font-bold text-white">JEL Knockouts</h2>
                <p className="text-orange-400 text-xs font-semibold uppercase tracking-wider">JPL Europa League</p>
              </div>
            </div>
            {(() => {
              const uelQF = data.challenger.c31 ?? data.challenger.c34 ?? [];
              const uelSF = data.challenger.c35 ?? data.challenger.c37 ?? [];
              const uelFinal = data.challenger.c36 ?? data.challenger.c38 ?? [];
              const hasData = uelQF.length > 0 || uelSF.length > 0 || uelFinal.length > 0;
              return hasData ? (
                <div className="overflow-x-auto -mx-4 px-4 sm:mx-0 sm:px-0">
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 min-w-[480px]">
                    <RoundColumn title="Quarter-Finals" ties={uelQF}liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} className="border-l-2 border-orange-500/30 pl-3" />
                    <RoundColumn title="Semi-Finals" ties={uelSF}liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} className="border-l-2 border-orange-500/30 pl-3" />
                    <RoundColumn title="JEL Final 🏆" ties={uelFinal}liveScores={data.liveScores} refreshingGw={refreshing} tempLiveScores={tempLiveScores} onRefreshRound={handleRefreshRound} className="border-l-2 border-orange-400/50 pl-3" />
                  </div>
                </div>
              ) : (
                <div className="rounded-xl border border-orange-500/20 bg-orange-500/5 px-5 py-6 text-sm text-orange-300">
                  JEL bracket will be generated after the group stage (GW24).
                </div>
              );
            })()}
          </div>
        )}
      </div>
    </div>
  );
}
