/**
 * Generate importable row-arrays for a league's full backup.
 *
 * Each returned array matches the column shape expected by the corresponding
 * import-* POST endpoint, so `JSON.stringify({ teams })` / `{ fixtures }` /
 * `{ captains }` / `{ chips }` round-trip cleanly.
 *
 * The backup endpoint (`/api/admin/[leagueId]/backup`) wraps these arrays into
 * .xlsx files via the `xlsx` lib and zips them. The auto-snapshot path stores
 * the same arrays as JSON in the `backups` table — re-formatting later just
 * means re-running the xlsx writer over the stored JSON.
 *
 * Skipping rules:
 *   - teams + captains arrays are null when format === "auction"
 *     (auction has its own onboarding; bulk-upload-teams refuses auction).
 *   - chips array is null when format !== "tvt" (only TVT uses gameweekChips).
 */

import { db } from "@/lib/db";
import { leagues, teams, gameweeks, fixtures, gameweekCaptains, gameweekChips, auctionOwnership, auctionClubOwnership } from "@/lib/db/schema";
import { eq, and, inArray } from "drizzle-orm";

export type TeamRow = {
  "Team ID": string;
  "Team Name": string;
  Password: string;
  "Player1 Name": string;
  "Player1 FPL ID": string;
  "Player2 Name": string;
  "Player2 FPL ID": string;
  Group: string;
};

export type FixtureRow = {
  Gameweek: number;
  "Home Team": string;
  "Away Team": string;
};

// Captain rows have static Team + Players cols + dynamic 1..38 GW cols.
export type CaptainRow = Record<string, string>;

// Chip rows have a static Team col + dynamic 1..38 GW cols.
export type ChipRow = Record<string, string>;

// Auction sheets — populated only for `format === "auction"`. Use stable column names so the
// restore endpoint and Excel viewers can both read them.
export type AuctionTeamStateRow = {
  "Team ID": string;
  "Team Login ID": string;
  "Team Name": string;
  Purse: number;
  "Total Spent": number;
  "Total Income": number;
  "Total Refunds": number;
  "Penalty Slots": number;
  "Bonus Slots": number;
};
export type AuctionSquadRow = {
  "Ownership ID": string;
  "Team ID": string;
  "FPL Element ID": number;
  "Player Name": string;
  "Element Type": number | null;
  "Purchase Price": number;
  "Acquired GW": number;
  "Released GW": number | null;
  Status: string;
};
export type AuctionClubRow = {
  ID: string;
  "Team ID": string;
  "PL Team ID": number;
  "PL Team Name": string;
  "PL Team Short": string;
  Tier: string;
  "Purchase Price": number;
  "Acquired At": string;
};
export type GameweekRow = {
  ID: string;
  Number: number;
  Deadline: string;
  "Is Playoffs": boolean;
};

export type BackupRows = {
  format: string;
  teams: TeamRow[] | null;
  fixtures: FixtureRow[];
  captains: CaptainRow[] | null;
  chips: ChipRow[] | null;
  // Auction-only sheets — null for TVT / triple-crown.
  auctionTeamsState: AuctionTeamStateRow[] | null;
  auctionSquads: AuctionSquadRow[] | null;
  auctionClubs: AuctionClubRow[] | null;
  // Available for every format — the restore endpoint reads this when recreating GW rows.
  gameweeks: GameweekRow[];
};

/**
 * Placeholder password emitted for every team in the backup. Bcrypt hashes
 * cannot be reversed, and re-importing requires plaintext (bulk-upload-teams
 * re-hashes via bcrypt). On restore, admin must hand out new passwords or use
 * the per-team "edit team" flow to set them.
 */
const PASSWORD_PLACEHOLDER = "RESET_REQUIRED";

export async function generateBackupRows(leagueId: string): Promise<BackupRows> {
  const [league] = await db
    .select({ id: leagues.id, format: leagues.format })
    .from(leagues)
    .where(eq(leagues.id, leagueId))
    .limit(1);
  if (!league) throw new Error(`League ${leagueId} not found`);

  // ── Teams + players + group ──
  let teamsRows: TeamRow[] | null = null;
  if (league.format !== "auction") {
    const teamRows = await db.query.teams.findMany({
      where: and(eq(teams.leagueId, leagueId), eq(teams.isGhost, false)),
      with: { players: true, group: true },
    });
    teamsRows = teamRows.map(t => {
      const [p1, p2] = t.players;
      return {
        "Team ID": t.teamLoginId ?? "",
        "Team Name": t.name,
        Password: PASSWORD_PLACEHOLDER,
        "Player1 Name": p1?.name ?? "",
        "Player1 FPL ID": p1?.fplId ?? "",
        "Player2 Name": p2?.name ?? "",
        "Player2 FPL ID": p2?.fplId ?? "",
        Group: t.group?.name ?? "",
      };
    });
  }

  // ── Fixtures (PL only — playoff fixtures are auto-generated by advance) ──
  const allGameweeks = await db
    .select({ id: gameweeks.id, number: gameweeks.number })
    .from(gameweeks)
    .where(eq(gameweeks.leagueId, leagueId));
  const gwIdToNumber = new Map(allGameweeks.map(gw => [gw.id, gw.number]));
  const allGwIds = allGameweeks.map(gw => gw.id);

  const fixturesData = allGwIds.length === 0 ? [] : await db.query.fixtures.findMany({
    where: and(inArray(fixtures.gameweekId, allGwIds), eq(fixtures.isPlayoff, false)),
    with: { homeTeam: true, awayTeam: true },
  });
  const fixturesRows: FixtureRow[] = fixturesData
    .map(f => ({
      Gameweek: gwIdToNumber.get(f.gameweekId) ?? 0,
      "Home Team": f.homeTeam?.teamLoginId ?? "",
      "Away Team": f.awayTeam?.teamLoginId ?? "",
    }))
    .filter(r => r.Gameweek > 0 && r["Home Team"] && r["Away Team"])
    .sort((a, b) => a.Gameweek - b.Gameweek);

  // ── Captains: one row per (team, player); cell n = "C" if that player was captain in GW n ──
  let captainsRows: CaptainRow[] | null = null;
  if (league.format !== "auction" && allGwIds.length > 0) {
    const captainRows = await db.query.gameweekCaptains.findMany({
      where: inArray(gameweekCaptains.gameweekId, allGwIds),
      with: { player: { with: { team: true } } },
    });
    // Index by playerId × gw → "C"
    const captainByPlayerGw = new Map<string, Set<number>>();
    for (const c of captainRows) {
      if (!c.player?.id) continue;
      const gwNum = gwIdToNumber.get(c.gameweekId);
      if (!gwNum) continue;
      let set = captainByPlayerGw.get(c.player.id);
      if (!set) { set = new Set(); captainByPlayerGw.set(c.player.id, set); }
      set.add(gwNum);
    }

    // Need teams+players ordering. Reuse the team query above when not auction
    const teamsForCaptains = teamsRows
      ? await db.query.teams.findMany({
          where: and(eq(teams.leagueId, leagueId), eq(teams.isGhost, false)),
          with: { players: true },
        })
      : [];

    captainsRows = [];
    for (const t of teamsForCaptains) {
      for (const p of t.players) {
        const captainGws = captainByPlayerGw.get(p.id) ?? new Set();
        const row: CaptainRow = {
          Team: t.teamLoginId ?? "",
          Players: p.name,
        };
        for (let gw = 1; gw <= 38; gw++) {
          row[String(gw)] = captainGws.has(gw) ? "C" : "";
        }
        captainsRows.push(row);
      }
    }
  }

  // ── Chips: one row per team; cell n = chip code or "" ──
  let chipsRows: ChipRow[] | null = null;
  if (league.format === "tvt" && allGwIds.length > 0) {
    const chipsData = await db.query.gameweekChips.findMany({
      where: inArray(gameweekChips.gameweekId, allGwIds),
      with: { team: true, challengedTeam: true },
    });

    // Index by teamId × gw → encoded chip cell value
    const chipsByTeamGw = new Map<string, Map<number, string>>();
    for (const c of chipsData) {
      const gwNum = gwIdToNumber.get(c.gameweekId);
      if (!gwNum || !c.teamId) continue;
      const code = encodeChipCell(c.chipType, c.isValid, c.challengedTeam?.teamLoginId ?? null);
      if (!code) continue;
      let perTeam = chipsByTeamGw.get(c.teamId);
      if (!perTeam) { perTeam = new Map(); chipsByTeamGw.set(c.teamId, perTeam); }
      perTeam.set(gwNum, code);
    }

    const teamsForChips = await db.query.teams.findMany({
      where: and(eq(teams.leagueId, leagueId), eq(teams.isGhost, false)),
    });
    chipsRows = teamsForChips.map(t => {
      const perGw = chipsByTeamGw.get(t.id);
      const row: ChipRow = { Team: t.teamLoginId ?? "" };
      for (let gw = 1; gw <= 38; gw++) {
        row[String(gw)] = perGw?.get(gw) ?? "";
      }
      return row;
    });
  }

  // ── Gameweeks shape — id / number / deadline / isPlayoffs. Available for every format. ──
  const gwRows = await db
    .select({
      id: gameweeks.id,
      number: gameweeks.number,
      deadline: gameweeks.deadline,
      isPlayoffs: gameweeks.isPlayoffs,
    })
    .from(gameweeks)
    .where(eq(gameweeks.leagueId, leagueId));
  const gameweeksRows: GameweekRow[] = gwRows
    .map((g) => ({
      ID: g.id,
      Number: g.number,
      Deadline: g.deadline.toISOString(),
      "Is Playoffs": Boolean(g.isPlayoffs),
    }))
    .sort((a, b) => a.Number - b.Number);

  // ── Auction sheets — populated only for auction leagues. ──
  let auctionTeamsState: AuctionTeamStateRow[] | null = null;
  let auctionSquads: AuctionSquadRow[] | null = null;
  let auctionClubs: AuctionClubRow[] | null = null;
  if (league.format === "auction") {
    const [auctionTeamRows, ownershipRows, clubRows] = await Promise.all([
      db.select({
        id: teams.id,
        teamLoginId: teams.teamLoginId,
        name: teams.name,
        purse: teams.purse,
        totalSpent: teams.totalSpent,
        totalIncome: teams.totalIncome,
        totalRefunds: teams.totalRefunds,
        penaltySlots: teams.penaltySlots,
        bonusSlots: teams.bonusSlots,
      })
        .from(teams)
        .where(and(eq(teams.leagueId, leagueId), eq(teams.isGhost, false))),
      db.select().from(auctionOwnership).where(eq(auctionOwnership.leagueId, leagueId)),
      db.select().from(auctionClubOwnership).where(eq(auctionClubOwnership.leagueId, leagueId)),
    ]);

    auctionTeamsState = auctionTeamRows.map((t) => ({
      "Team ID": t.id,
      "Team Login ID": t.teamLoginId ?? "",
      "Team Name": t.name,
      Purse: t.purse,
      "Total Spent": t.totalSpent,
      "Total Income": t.totalIncome,
      "Total Refunds": t.totalRefunds,
      "Penalty Slots": t.penaltySlots,
      "Bonus Slots": t.bonusSlots ?? 0,
    }));

    auctionSquads = ownershipRows.map((o) => ({
      "Ownership ID": o.id,
      "Team ID": o.teamId,
      "FPL Element ID": o.fplElementId,
      "Player Name": o.playerName,
      "Element Type": o.elementType ?? null,
      "Purchase Price": o.purchasePrice,
      "Acquired GW": o.acquiredGw,
      "Released GW": o.releasedGw ?? null,
      Status: o.status,
    }));

    auctionClubs = clubRows.map((c) => ({
      ID: c.id,
      "Team ID": c.teamId,
      "PL Team ID": c.plTeamId,
      "PL Team Name": c.plTeamName,
      "PL Team Short": c.plTeamShort,
      Tier: c.tier,
      "Purchase Price": c.purchasePrice,
      "Acquired At": c.acquiredAt.toISOString(),
    }));
  }

  return {
    format: league.format,
    teams: teamsRows,
    fixtures: fixturesRows,
    captains: captainsRows,
    chips: chipsRows,
    auctionTeamsState,
    auctionSquads,
    auctionClubs,
    gameweeks: gameweeksRows,
  };
}

/**
 * Encode a stored gameweekChips row back into the cell value the import-chips
 * endpoint accepts. Mirrors the parse logic in `import-chips/route.ts:117-149`.
 *  - "W" / "D" / "C" / "SL" / "CB" / "UD" — valid chip
 *  - "WW" / "DW" / "CW" / "SLW" / "CBW" / "UDW" — wasted chip
 *  - "C:OPP" — Challenge Chip with opponent's teamLoginId
 */
function encodeChipCell(chipType: string, isValid: boolean, opponentLoginId: string | null): string {
  const validChips = new Set(["W", "D", "C", "SL", "CB", "UD"]);
  if (!validChips.has(chipType)) return "";
  // Wasted (round-trip marker — the parser treats W as 'wasted' suffix)
  if (!isValid) return `${chipType}W`;
  // Challenge Chip with opponent
  if (chipType === "C" && opponentLoginId) return `C:${opponentLoginId}`;
  return chipType;
}
