// @deprecated The Bulk Upload tab no longer exposes a Fixtures upload block — the unified
// Backup/Restore .zip now covers fixture restore. This endpoint stays for backwards compatibility;
// remove in a future pass.

import { NextRequest, NextResponse } from "next/server";
import { db, teams, groups, gameweeks, fixtures, leagues } from "@/lib/db";
import { eq, and, inArray } from "drizzle-orm";
import { generateId } from "@/lib/id";
import { getAuthorizedLeagueId } from "@/lib/league-auth";
import { invalidateLeaguePageCache } from "@/lib/fpl-cache";

interface FixtureRow {
  gameweek: string | number;
  homeTeamId: string; // Team Login ID
  awayTeamId: string; // Team Login ID
}

/**
 * POST /api/admin/[leagueId]/bulk-upload-fixtures
 * Admin-only endpoint to bulk upload fixtures from CSV data
 */
export async function POST(request: NextRequest) {
  try {
    const leagueId = await getAuthorizedLeagueId(request);
    if (!leagueId) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

    const body = await request.json();
    const { fixtures: fixtureRows, clearExisting } = body as {
      fixtures: FixtureRow[];
      clearExisting?: boolean;
    };

    if (!fixtureRows || !Array.isArray(fixtureRows) || fixtureRows.length === 0) {
      return NextResponse.json(
        { error: "No fixtures data provided" },
        { status: 400 }
      );
    }

    if (fixtureRows.length > 500) {
      return NextResponse.json(
        { error: "Too many rows. Maximum 500 fixtures per upload." },
        { status: 400 }
      );
    }

    const results: { success: string[]; errors: string[] } = {
      success: [],
      errors: [],
    };

    // Fetch league config
    const leagueRecord = await db
      .select({ playoffStartGw: leagues.playoffStartGw })
      .from(leagues)
      .where(eq(leagues.id, leagueId))
      .limit(1);
    if (!leagueRecord.length) return NextResponse.json({ error: "League not found" }, { status: 404 });
    const { playoffStartGw } = leagueRecord[0];

    // Get all teams for this league for lookup
    const allTeams = await db.query.teams.findMany({
      where: eq(teams.leagueId, leagueId),
      with: { group: true },
    });
    const teamMap = new Map(allTeams.map(t => [t.teamLoginId?.toLowerCase() || "", t]));

    // Get all gameweeks for this league for lookup
    const allGameweeks = await db.select().from(gameweeks).where(eq(gameweeks.leagueId, leagueId));
    const gameweekMap = new Map(allGameweeks.map(gw => [gw.number, gw]));

    // Optionally clear existing LEAGUE-STAGE fixtures (for re-upload). Playoff
    // fixtures (gameweeks.isPlayoffs=true) are preserved — they are generated by
    // /api/admin/[leagueId]/generate-playoffs and shouldn't be wiped by a
    // league-stage bulk re-upload. Mirrors the DELETE behaviour of /generate-fixtures.
    if (clearExisting) {
      const leagueStageGwIds = allGameweeks.filter(gw => !gw.isPlayoffs).map(gw => gw.id);
      if (leagueStageGwIds.length > 0) {
        await db.delete(fixtures).where(inArray(fixtures.gameweekId, leagueStageGwIds));
      }
    }

    // Process each fixture row
    for (let i = 0; i < fixtureRows.length; i++) {
      const row = fixtureRows[i];
      const rowNum = i + 2; // Excel row number (1-indexed + header)

      try {
        // Validate required fields
        if (!row.gameweek || !row.homeTeamId || !row.awayTeamId) {
          results.errors.push(`Row ${rowNum}: Missing required fields (gameweek, homeTeamId, awayTeamId)`);
          continue;
        }

        const gwNumber = typeof row.gameweek === 'string' ? parseInt(row.gameweek) : row.gameweek;
        if (isNaN(gwNumber) || gwNumber < 1 || gwNumber > 38) {
          results.errors.push(`Row ${rowNum}: Invalid gameweek number (must be 1-38)`);
          continue;
        }

        // Find home team
        const homeTeam = teamMap.get(row.homeTeamId.toLowerCase().trim());
        if (!homeTeam) {
          results.errors.push(`Row ${rowNum}: Home team "${row.homeTeamId}" not found`);
          continue;
        }

        // Find away team
        const awayTeam = teamMap.get(row.awayTeamId.toLowerCase().trim());
        if (!awayTeam) {
          results.errors.push(`Row ${rowNum}: Away team "${row.awayTeamId}" not found`);
          continue;
        }

        // Verify teams are in the same group
        if (homeTeam.groupId !== awayTeam.groupId) {
          results.errors.push(`Row ${rowNum}: Teams must be in the same group`);
          continue;
        }

        // Refuse to auto-create a missing gameweek with a synthetic deadline.
        // bulk-upload-fixtures previously synthesised `today + 7*N days` at 11:00,
        // which drifts the schedule from the real Premier League calendar and
        // also misclassified playoffs via `gwNumber >= null` when playoffStartGw
        // was unset. Admins must run create-gameweeks (real FPL deadlines) first.
        const gw = gameweekMap.get(gwNumber);
        if (!gw) {
          results.errors.push(
            `Row ${rowNum}: GW${gwNumber} does not exist for this league. Run create-gameweeks first to populate real FPL deadlines.`
          );
          continue;
        }
        // Also guard the misclassification: if the league's playoffStartGw column
        // somehow ended up null, refuse fixtures in the playoff range — they would
        // otherwise be stored as isPlayoffs=false and break downstream pipelines.
        if (playoffStartGw == null && gwNumber >= 31) {
          results.errors.push(
            `Row ${rowNum}: GW${gwNumber} is in the playoff range but this league has no playoffStartGw configured.`
          );
          continue;
        }

        // Check if fixture already exists
        const existingFixtures = await db.select().from(fixtures).where(
          and(
            eq(fixtures.gameweekId, gw.id),
            eq(fixtures.homeTeamId, homeTeam.id),
            eq(fixtures.awayTeamId, awayTeam.id)
          )
        );

        if (existingFixtures.length > 0) {
          results.errors.push(`Row ${rowNum}: Fixture already exists (GW${gwNumber}: ${row.homeTeamId} vs ${row.awayTeamId})`);
          continue;
        }

        // Create fixture
        await db.insert(fixtures).values({
          id: generateId(),
          gameweekId: gw.id,
          homeTeamId: homeTeam.id,
          awayTeamId: awayTeam.id,
          groupId: homeTeam.groupId,
        });

        results.success.push(`Row ${rowNum}: GW${gwNumber} - ${row.homeTeamId} vs ${row.awayTeamId} created`);
      } catch (error) {
        console.error(`Error processing row ${rowNum}:`, error);
        results.errors.push(`Row ${rowNum}: ${error instanceof Error ? error.message : "Unknown error"}`);
      }
    }

    await invalidateLeaguePageCache(leagueId);
    return NextResponse.json({
      message: `Processed ${fixtureRows.length} rows`,
      created: results.success.length,
      failed: results.errors.length,
      details: results,
    });
  } catch (error) {
    console.error("Bulk upload fixtures error:", error);
    return NextResponse.json(
      { error: "Failed to process bulk upload" },
      { status: 500 }
    );
  }
}

/**
 * GET /api/admin/[leagueId]/bulk-upload-fixtures
 * Get template structure for fixture upload
 */
export async function GET(request: NextRequest) {
  const leagueId = await getAuthorizedLeagueId(request);
  if (!leagueId) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  // Get existing teams for this league for reference
  const allTeams = await db.query.teams.findMany({
    where: eq(teams.leagueId, leagueId),
    with: { group: true },
  });

  return NextResponse.json({
    template: {
      columns: ["Gameweek", "Home Team", "Away Team", "Deadline"],
      example: ["1", "DM — Rahul", "SK — Arjun", "2026-03-15 11:00"],
    },
    csvHeader: "Gameweek,Home Team,Away Team,Deadline",
    csvExample: "1,DM — Rahul,SK — Arjun,2026-03-15 11:00",
    existingTeams: allTeams.map(t => ({
      name: t.name,
      group: t.group?.name || "Unassigned",
    })),
  });
}
